package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public void setStuid(java.lang.Integer stuid) {
		set("stuid", stuid);
	}
	
	public java.lang.Integer getStuid() {
		return getInt("stuid");
	}

	public void setStuname(java.lang.String stuname) {
		set("stuname", stuname);
	}
	
	public java.lang.String getStuname() {
		return getStr("stuname");
	}

	public void setStuage(java.lang.String stuage) {
		set("stuage", stuage);
	}
	
	public java.lang.String getStuage() {
		return getStr("stuage");
	}

}
